### ISSUE TITLE
thin saving in code issue

### ISSUE THREAD

**Issue by jacklu1024** [IBM/ibm-storage-odf-block-driver#10]
in the  pkg/collectors/pool.go , below line seems not correct.  Why totalsaving is savingsthin?

                thinSavings := math.Max(0, tempValue)

		log.Infof("pool: %d, thin saving: %f", poolInfo.PoolId, thinSavings)
		newPoolCapacityMetrics(ch, f.poolDescriptors[PoolEfficiencySavingsThin], **_totalSaving_**, &poolInfo)

**Comment by xuezhiy** [comment]
Fixed by pr https://github.com/IBM/ibm-storage-odf-block-driver/pull/11
